import os

# --- FILE PATHS ---
DATA_DIR = "data"
DATA_FILE = "salary.json"
INPUT_FILE_PATH = os.path.join(DATA_DIR, DATA_FILE)

# --- PAYROLL CONFIGURATION ---
RATE_SSS = 0.045
RATE_PHILHEALTH = 0.025
RATE_PAGIBIG = 0.020
RATE_TAX = 0.10

# --- GENERATOR SETTINGS ---
GEN_EMPLOYEE_COUNT = 5
GEN_MIN_SALARY = 10000
GEN_MAX_SALARY = 100000